apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-vtfe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-vtfe
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-vtfe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-vtfe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-vtfe
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ghpl-tenant/status-quarkus-io/statusquarkusio-vtfe@sha256:65e84b53e9ebc4d4e0f84c85b28e5afb8e7293b5a04d76b1ea0811c88caf0019
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
